steer_bot_hardware_gazebo:
  rear_wheel: 'rear_wheel_joint'
  front_steer: 'front_steer_joint'
  virtual_rear_wheels  : ['base_to_blw', 'base_to_brw']
  virtual_front_wheels : ['base_to_flw', 'base_to_frw']
  virtual_front_steers : ['steer_left_joint', 'steer_right_joint']

  # ackermann link mechanism
  enable_ackermann_link: true
  wheel_separation_w : 0.5
  wheel_separation_h : 0.79